### PR TITLE
Changed default configuration removing user creation capabilities

### PR DESCRIPTION
**Pull request by james-cccc**
Changed the default configuration of the Quay registry disabling user creation as it isn't somthing that should be required by default

### CODE REVIEW

**Comment by ibazulic** [comment]
This would severely impact all installations of Quay. I fail to see why would the default settings be so restrictive, not to mention it would cause confusion to everyone that install Quay for the first time. If a user wants to disable user creation, they can do so by setting these manually in their `config.yaml` file.

**Comment by james-cccc** [comment]
I'm thinking thought as this is just a container registry that is supposed to be used for just the bootstrap and usage of OCP cluster this change shouldn't really be impacting to anyone here? I personally can't think of a need to create an account here for the use case that this standalone mirror registry was put together for.  

However, what I can do if you have no objection is to amend the PR so its possible to set a flag to set this through the install?  - the reason I'm asking is that IHAC in a secure env that cannot have this enabled be default and even though you can change this after the fact it's not ideal for them. It'd really help me out a lot and I'm happy to put the work in here.

**Comment by ibazulic** [comment]
From my (support) experience, people still create several accounts on the mirror registry as well, since they usually don't have just one person maintaining it :-) They also sometimes link the mirror registry with LDAP after installation thereby actually requiring the registry to have the user initalization enabled. 

IMHO the setting to disable user creation should be an option added to the installer, not change the default setting. Something like `--disableUserCreation` with the value being `false` if not defined.

**Comment by HammerMeetNail** [comment]
We're seeing a lot of requests to add common config options as cli options. Would having a cli option that accepts a custom config be a good middle ground? I think the alternative is to play whack-a-mole with mapping config options to cli options.

**Pull request closed without merging**
