### PR TITLE
allow to specify initUser

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
@karmab Thanks for getting this in, running it through CI now.

**Comment by HammerMeetNail** [comment]
This looks good, expecting to merge in the next day or two after I've had a chance to test it out locally.

**Comment by HammerMeetNail** [comment]
Verified, thanks @karmab

**Review by HammerMeetNail — APPROVED** [review]
LGTM 👍

**Comment by sshnaidm** [comment]
Worth to add to README:  https://github.com/quay/mirror-registry/blob/main/README.md?plain=1#L27

**Pull request merged**
